apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: fastapi
  labels:
    app: fastapi
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/instance: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
        app.kubernetes.io/name: fastapi
    spec:
      containers:
      - name: fastapi
        image: juanse1796/fastapi-mlops:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "/models/model.pkl"
        volumeMounts:
        - name: model-volume
          mountPath: /models
          readOnly: true
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
      volumes:
      - name: model-volume
        hostPath:
          path: /home/estudiante/model.pkl 
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi
  labels:
    app: fastapi
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP